// Code Generated by Sidekick is for learning and experimentation purposes only.
function main(workbook: ExcelScript.Workbook) {
  let sheet = workbook.getActiveWorksheet();
  let usedRange = sheet.getUsedRange();
  let rowCount = usedRange.getRowCount();
  let colCount = usedRange.getColumnCount();

  // Data starts at row 6 (zero-based index 5)
  // "Debit"/"Credit" in column O (zero-based index 14)
  for (let i = 5; i < rowCount; i++) {
    let typeCell = sheet.getCell(i, 14); // Column O
    let typeValue = typeCell.getValue();
    let rowRange = sheet.getRangeByIndexes(i, 0, 1, colCount);

    if (typeValue && typeof typeValue === "string") {
      if (typeValue.trim().toLowerCase() === "debit") {
        rowRange.getFormat().getFill().setColor("#E68887"); // Red
      } else if (typeValue.trim().toLowerCase() === "credit") {
        rowRange.getFormat().getFill().setColor("#D8E4BC"); // Green
      }
    }
  }

  // Sort by column P (zero-based index 15), ascending
  // Sort range: from header row (row 5) to last row, all columns
  let sortRange = sheet.getRangeByIndexes(5, 0, rowCount - 5, colCount);
  sortRange.getSort().apply([
    {
      key: 15, // Column P
      ascending: true
    }
  ], false);
}
