// Code Generated by Sidekick is for learning and experimentation purposes only.
function main(workbook: ExcelScript.Workbook) {
  let sheet = workbook.getActiveWorksheet();

  // Get used range
  let usedRange = sheet.getUsedRange();
  let rowCount = usedRange.getRowCount();
  let colCount = usedRange.getColumnCount();

  // Assuming header is in row 1, and "type" is column 5 (E), "date" is column 6 (F)
  for (let i = 1; i < rowCount; i++) { // Start from 1 to skip header
    let typeCell = sheet.getCell(i, 4); // Column E (zero-based index 4)
    let typeValue = typeCell.getValue();

    let rowRange = sheet.getRangeByIndexes(i, 0, 1, colCount);

    if (typeValue && typeof typeValue === "string") {
      if (typeValue.trim().toLowerCase() === "debit") {
        rowRange.getFormat().getFill().setColor("#F7C7AC"); // Light Red
      } else if (typeValue.trim().toLowerCase() === "credit") {
        rowRange.getFormat().getFill().setColor("#B5E6A2"); // Light Green
      }
    }
  }

  // Sort by "date" column (column 6, zero-based index 5), descending (newest to oldest)
  usedRange.getSort().apply([
    {
      key: 5, // Column F (date)
      ascending: false
    }
  ], false);

}
